// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import '@databricks/appkit-ui/react';
import type { SQLStringMarker } from '@databricks/appkit-ui/js';

declare module '@databricks/appkit-ui/react' {
  interface QueryRegistry {
    exception_detail: {
      name: 'exception_detail';
      parameters: {
        /** STRING - use sql.string() */
        exception_id: SQLStringMarker;
      };
      result: Array<{
        /** @sqlType STRING */
        exception_id: string;
        /** @sqlType STRING */
        reference_id: string;
        /** @sqlType STRING */
        account_name: string;
        /** @sqlType STRING */
        check_type: string;
        /** @sqlType STRING */
        severity: string;
        /** @sqlType DOUBLE */
        amount_at_risk: number;
        /** @sqlType STRING */
        detection_method: string;
        /** @sqlType STRING */
        source_table: string;
        /** @sqlType BIGINT */
        customer_id: number;
        /** @sqlType BOOLEAN */
        known_leakage_flag: boolean;
        /** @sqlType STRING */
        risk_tier: string;
        /** @sqlType DOUBLE */
        composite_health_score: number;
        /** @sqlType STRING */
        arpu_tier: string;
        /** @sqlType STRING */
        billing_currency: string;
        /** @sqlType STRING */
        account_status: string;
        /** @sqlType DOUBLE */
        price_accuracy_score: number;
        /** @sqlType DOUBLE */
        discount_compliance_score: number;
        /** @sqlType DECIMAL(4,1) */
        collection_efficiency_score: number;
        /** @sqlType DOUBLE */
        doc_consistency_score: number;
        /** @sqlType BIGINT */
        customer_total_exceptions: number;
        /** @sqlType DOUBLE */
        customer_total_at_risk: number;
      }>;
    };
  }
}
