// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    exception_detail: {
        name: "exception_detail";
        parameters: {
          /** STRING - use sql.string() */
          exception_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          exception_id: string;
          /** @sqlType STRING */
          reference_id: string;
          /** @sqlType STRING */
          account_name: string;
          /** @sqlType STRING */
          check_type: string;
          /** @sqlType STRING */
          severity: string;
          /** @sqlType DOUBLE */
          amount_at_risk: number;
          /** @sqlType STRING */
          detection_method: string;
          /** @sqlType STRING */
          source_table: string;
          /** @sqlType BIGINT */
          customer_id: number;
          /** @sqlType BOOLEAN */
          known_leakage_flag: boolean;
          /** @sqlType STRING */
          risk_tier: string;
          /** @sqlType DOUBLE */
          composite_health_score: number;
          /** @sqlType STRING */
          arpu_tier: string;
          /** @sqlType STRING */
          billing_currency: string;
          /** @sqlType STRING */
          account_status: string;
          /** @sqlType DOUBLE */
          price_accuracy_score: number;
          /** @sqlType DOUBLE */
          discount_compliance_score: number;
          /** @sqlType DECIMAL(4,1) */
          collection_efficiency_score: number;
          /** @sqlType DOUBLE */
          doc_consistency_score: number;
          /** @sqlType BIGINT */
          customer_total_exceptions: number;
          /** @sqlType DOUBLE */
          customer_total_at_risk: number;
        }>;
      };
    exceptions_list: {
        name: "exceptions_list";
        parameters: {
          /** STRING - use sql.string() */
          check_type: SQLStringMarker;
          /** STRING - use sql.string() */
          severity: SQLStringMarker;
          /** STRING - use sql.string() */
          search: SQLStringMarker;
          /** INT - use sql.int() */
          row_limit: SQLNumberMarker;
          /** INT - use sql.int() */
          row_offset: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          exception_id: string;
          /** @sqlType STRING */
          reference_id: string;
          /** @sqlType STRING */
          account_name: string;
          /** @sqlType STRING */
          check_type: string;
          /** @sqlType STRING */
          severity: string;
          /** @sqlType DOUBLE */
          amount_at_risk: number;
          /** @sqlType STRING */
          detection_method: string;
          /** @sqlType STRING */
          source_table: string;
          /** @sqlType BIGINT */
          customer_id: number;
          /** @sqlType BOOLEAN */
          known_leakage_flag: boolean;
        }>;
      };
    kpi_summary: {
        name: "kpi_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          total_exceptions: number;
          /** @sqlType DOUBLE */
          total_at_risk: number;
          /** @sqlType BIGINT */
          high_severity: number;
          /** @sqlType BIGINT */
          accounts_affected: number;
        }>;
      };
    rootcause_breakdown: {
        name: "rootcause_breakdown";
        parameters: {
          /** STRING - use sql.string() */
          severity: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          check_type: string;
          /** @sqlType BIGINT */
          exception_count: number;
          /** @sqlType DOUBLE */
          amount_at_risk: number;
        }>;
      };
  }
}
